name: Build and Publish Docker Images

on:
  push:
    branches: [ main ]
  release:
    types: [ created ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push API Gateway image
      uses: docker/build-push-action@v4
      with:
        context: ./api-gateway
        push: true
        tags: ${{ steps.meta.outputs.tags }}-api-gateway
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push Transaction Service image
      uses: docker/build-push-action@v4
      with:
        context: ./transaction-service
        push: true
        tags: ${{ steps.meta.outputs.tags }}-transaction-service
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push Anti-Fraud Service image
      uses: docker/build-push-action@v4
      with:
        context: ./anti-fraud-service
        push: true
        tags: ${{ steps.meta.outputs.tags }}-anti-fraud-service
        labels: ${{ steps.meta.outputs.labels }}

    - name: Build and push Status Update Service image
      uses: docker/build-push-action@v4
      with:
        context: ./status-update-service
        push: true
        tags: ${{ steps.meta.outputs.tags }}-status-update-service
        labels: ${{ steps.meta.outputs.labels }}